name: flutter_cached_pdfview
description: A package to show Native PDF View for iOS and Android, support Open
  from a different resource like Path, Asset or Url and Cache it.
version: 0.3.5
homepage: https://abdosaed.ml/
repository: https://github.com/AbdOoSaed/flutter_cached_pdfview
issue_tracker: https://github.com/AbdOoSaed/flutter_cached_pdfview/issues
environment:
  sdk: ">=2.6.0 <3.0.0"
# new pubspec
#https://flutter.dev/docs/development/packages-and-plugins/developing-packages
dependencies:
  flutter:
    sdk: flutter
  
  flutter_cache_manager: ^2.1.1
  flutter_pdfview: 
    git:
        url: https://github.com/Lykeosovandara/Flutter_PdfView.git
        path: flutter_pdfview
  path: ^1.6.4
  path_provider: '>=1.4.5 <=2.0.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
